### PR TITLE
Add connection name for model Two2FA and fixes some translations keys

### PR DESCRIPTION
**Pull request by ElRochito**
Hi,

This PR allows to customize connection name of TwoAFA model.
Indeed, I work on a multi tenant website and some migrations are on a different connection

@lahirulhr

### CODE REVIEW

**Review by lahirulhr — APPROVED** [review]

**Comment by lahirulhr** [comment]
@ElRochito 

Thank you so much for the improvements & contribution.

**Comment by ElRochito** [comment]
@lahirulhr When do you plan to release it ?

**Comment by lahirulhr** [comment]
> @lahirulhr When do you plan to release it ?

Minor version will be published tomorrow.

**Comment by ElRochito** [comment]
> > @lahirulhr When do you plan to release it ?
> 
> Minor version will be published tomorrow.

Ok thanks

**Pull request merged**
